# @name list-prompts
GET http://localhost:3333/prompts

###

# @name upload-video
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="audio"; filename="example.mp3"
Content-Type: audio/mpeg

< ./example.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription
POST http://localhost:3333/videos/1b703029-4f20-4985-885d-923a5994f768/transcription
Content-Type: application/json

{
  "prompt": "clean architecture, ddd"
}

###

# @name generate-ai-completion
POST http://localhost:3333/ai/completion
Content-Type: application/json

{
  "temperature": 0.5,
  "template": "Generate a bref summary of the following video transcription: ```{transcription}```",
  "videoId": "1b703029-4f20-4985-885d-923a5994f768"
}
